In [1]:
from gym_smartgrid.envs import SmartGridEnv6
import pandas as pd

In [2]:
env = SmartGridEnv6()
env.reset()
for _ in range(50):
    env.render('save')
    env.step(env.action_space.sample()) # take a random action
history = env.close(path='test_history.csv')

In [3]:
loaded_history = pd.read_csv('test_history.csv', )

In [4]:
history.head()

,network_specs,obs,potential,time
0,"([0.0, -1.0, 2.0, -1.0, 1.0, -1.0], [-100.0, -...",NaN,NaN,NaT
1,NaN,"([0.11347317005797208, 0.0, 0.0, 0.0, 1.626592...","[0.0, 8.135715747170543]",2019-03-17 00:15:00
2,NaN,"([-7.116024476235482, 0.0, 0.0, 0.0, 2.9882166...","[0.0, 13.167469594124487]",2019-03-17 00:30:00
3,NaN,"([-7.540801950308919, 0.0, 0.0, 0.0, 8.4714287...","[0.0, 8.471428710583693]",2019-03-17 00:45:00
4,NaN,"([-3.760500892131887, 0.0, 0.0, 0.0, 3.8521771...","[0.0, 6.315252298702081]",2019-03-17 01:00:00

In [5]:
loaded_history.head()

,network_specs,obs,potential,time
0,"([0.0, -1.0, 2.0, -1.0, 1.0, -1.0], [-100.0, -...",NaN,NaN,NaN
1,NaN,"([0.11347317005797208, 0.0, 0.0, 0.0, 1.626592...","[0.0, 8.135715747170543]",2019-03-17 00:15:00
2,NaN,"([-7.116024476235482, 0.0, 0.0, 0.0, 2.9882166...","[0.0, 13.167469594124487]",2019-03-17 00:30:00
3,NaN,"([-7.540801950308919, 0.0, 0.0, 0.0, 8.4714287...","[0.0, 8.471428710583693]",2019-03-17 00:45:00
4,NaN,"([-3.760500892131887, 0.0, 0.0, 0.0, 3.8521771...","[0.0, 6.315252298702081]",2019-03-17 01:00:00

In [6]:
ns = loaded_history.network_specs[0]

In [7]:
import ast

In [8]:
obs = loaded_history.obs[1:]

In [9]:
obs

1     ([0.11347317005797208, 0.0, 0.0, 0.0, 1.626592...
2     ([-7.116024476235482, 0.0, 0.0, 0.0, 2.9882166...
3     ([-7.540801950308919, 0.0, 0.0, 0.0, 8.4714287...
4     ([-3.760500892131887, 0.0, 0.0, 0.0, 3.8521771...
5     ([-9.352752950035068, 0.0, 0.0, 0.0, 12.834554...
6     ([-5.448239419333248, 0.0, 0.0, 0.0, 4.1009704...
7     ([-7.7454780832193535, 0.0, 0.0, 0.0, 6.106450...
8     ([0.5943303791236474, 0.0, 0.0, 0.0, 2.4323351...
9     ([-2.7080913928799077, 0.0, 0.0, 0.0, 2.303458...
10    ([-9.42544238246279, 0.0, 0.0, 0.0, 7.56470356...
11    ([1.9040748773372231, 0.0, 0.0, 0.0, 0.6389376...
12    ([-6.5381525523255855, 0.0, 0.0, 0.0, 7.589442...
13    ([-3.522049677536302, 0.0, 0.0, 0.0, 2.4120268...
14    ([-3.3803856606352554, 0.0, 0.0, 0.0, 7.309172...
15    ([-7.738237344615271, 0.0, 0.0, 0.0, 4.5834670...
16    ([-3.9913633266057507, 0.0, 0.0, 0.0, 6.729443...
17    ([-4.360270886736828, 0.0, 0.0, 0.0, 6.9673912...
18    ([-0.31304370735688286, 0.0, 0.0, 0.0, 2.99560...
19    ([-2.4214243372079807, 0.0, 0.0, 0.0, 4.669976...
20    ([-6.465349582185638, 0.0, 0.0, 0.0, 9.1781760...
21    ([-7.16129369871669, 0.0, 0.0, 0.0, 9.39316495...
22    ([-5.017391062301982, 0.0, 0.0, 0.0, 8.9622580...
23    ([-8.08046082976199, 0.0, 1.3754605990128534, ...
24    ([-6.367947812511801, 0.0, 0.0, 0.0, 4.3591957...
25    ([-9.32908212961135, 0.0, 0.0, 0.0, 5.58026064...
26    ([-1.2443530655122004, 0.0, 0.0, 0.0, 1.056853...
27    ([-6.222499414939136, 0.0, 0.0, 0.0, 8.1011305...
28    ([-3.6977602145654203, 0.0, 1.9194239047925956...
29    ([-4.88384098739121, 0.0, 0.0, 0.0, 3.83264756...
30    ([-3.6068246616623867, 0.0, 0.0, 0.0, 6.663534...
31    ([-12.52563910838393, 0.0, 2.51803212057217, 0...
32    ([2.827542597183509, 0.0, 0.6270717978477478, ...
33    ([-11.334321293575897, 0.0, 2.706113631730169,...
34    ([-8.419698036438746, 0.0, 3.391957699797667, ...
35    ([-5.40121869846314, 0.0, 0.27736705548136, 0....
36    ([-17.79676669961222, 0.0, 6.653866196695006, ...
37    ([-18.161823453825946, 0.0, 7.874722733290569,...
38    ([-3.270202566072982, 0.0, 1.1262493133544922,...
39    ([-11.175841492834508, 0.0, 7.290275343348722,...
40    ([-16.113906357519685, 0.0, 9.24374008178711, ...
41    ([-13.892775596691054, 0.0, 8.532052348972769,...
42    ([-1.7247132429017427, 0.0, 1.1490553617477417...
43    ([-5.314079322374738, 0.0, 6.865495204925537, ...
44    ([-16.05334022710528, 0.0, 16.391229911696097,...
45    ([-4.493574677607967, 0.0, 6.135220527648926, ...
46    ([-18.60034353289325, 0.0, 15.960215438496935,...
47    ([-5.189638146465768, 0.0, 2.628962993621826, ...
48    ([-19.308390918867843, 0.0, 11.12506103515625,...
49    ([-23.141353580304582, 0.0, 9.976984024047852,...
Name: obs, dtype: object

In [10]:
type(history.obs[1:])

pandas.core.series.Series